name: Update GitHub Stats

on:
  schedule:
    # - cron: "0 */12 * * *"   # every 12 hours
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anuraghazra/github-readme-stats@main
        with:
          token: ${{ secrets.TOKEN }}